//! mirage-vision
//!
//! XTLS-Vision (`xtls-rprx-vision`) flow markers. Vision is the post-handshake
//! framing layer that goes on top of plain VLESS-over-Reality streams. Its
//! purpose is twofold:
//!
//! 1. **Padding the first few application-data records** to defeat passive
//!    traffic-size fingerprinting that would otherwise pick out short proxy
//!    requests.
//! 2. **Splicing**: once the inner stream confirms it carries real TLS
//!    traffic to its true destination, Vision asks both ends to drop down
//!    into a pure-copy fast path that bypasses any further user-mode
//!    encryption layers (because TLS is already authenticated).
//!
//! The 32-byte command word that switches the flow into the splice phase
//! is generated by `command_bytes()`. The padding helpers expose a
//! deterministic record-padding scheme parameterised by an interior seed
//! (typically derived from `RequestAddons::seed`).

#![forbid(unsafe_code)]
#![warn(clippy::pedantic)]
#![allow(clippy::missing_errors_doc, clippy::module_name_repetitions)]

use bytes::{BufMut, BytesMut};
use rand::Rng;

/// 32-byte "transition into splice mode" marker. Both ends agree on this
/// constant; once it appears in either direction the implementation can
/// switch the stream into bidirectional `tokio::io::copy_bidirectional`.
pub const VISION_MAGIC_PADDING: [u8; 8] = [b'V', b'i', b's', b'i', b'o', b'n', b'1', b'\n'];

/// Render the padding command bytes that prefix the first VLESS record in
/// Vision flows. The output is the same shape Xray emits: 8 bytes of
/// "Vision1\n" + 24 random bytes of cover.
#[must_use]
pub fn command_bytes() -> [u8; 32] {
    let mut out = [0u8; 32];
    out[..8].copy_from_slice(&VISION_MAGIC_PADDING);
    rand::thread_rng().fill(&mut out[8..]);
    out
}

/// Detect whether a buffer begins with a Vision padding command. Used by
/// the engine's splice-mode trigger.
#[must_use]
pub fn detect_command(buf: &[u8]) -> bool {
    buf.len() >= 8 && buf[..8] == VISION_MAGIC_PADDING
}

/// Light-weight TLS handshake detector. Returns the inner length when the
/// buffer begins with a TLS record header (`type = 22`, version = 0x0301..=0x0304),
/// otherwise `None`.
#[must_use]
pub fn parse_tls_handshake_record(buf: &[u8]) -> Option<u16> {
    if buf.len() < 5 {
        return None;
    }
    // type: handshake (0x16) + version major 0x03
    if buf[0] != 0x16 || buf[1] != 0x03 {
        return None;
    }
    Some(u16::from_be_bytes([buf[3], buf[4]]))
}

/// Compute a randomized padding length for the next Vision-wrapped record.
/// The distribution is centred around 500 bytes and capped at the maximum
/// TLS record size (16 KiB).
#[must_use]
pub fn random_padding_len() -> usize {
    rand::thread_rng().gen_range(0..=900)
}

/// Append `len` bytes of zero-padding into `out`.
pub fn write_padding(out: &mut BytesMut, len: usize) {
    out.reserve(len);
    for _ in 0..len {
        out.put_u8(0);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detects_own_command_bytes() {
        let cmd = command_bytes();
        assert!(detect_command(&cmd));
        assert!(!detect_command(b"hello world"));
    }

    #[test]
    fn parses_tls_handshake_header() {
        // ClientHello record header: handshake (0x16), TLS1.0 (0x03 0x01), length 0x0040
        let buf = [0x16, 0x03, 0x01, 0x00, 0x40];
        assert_eq!(parse_tls_handshake_record(&buf), Some(0x40));
        assert_eq!(parse_tls_handshake_record(&[0x17, 0x03, 0x03, 0, 5]), None);
    }
}
